-- Creación de la tabla VentasProductoA
CREATE TABLE SalesPA (
    SALE_DATE DATE NOT NULL,
    TOTAL_AMOUNT DECIMAL(18, 2) NOT NULL,
    PRODUCT_CODE VARCHAR(50) NOT NULL,
    PRODUCT_TYPE VARCHAR(50) NOT NULL
);

-- Creación de la tabla VentasProductoB
CREATE TABLE SalesPB (
    SALE_DATE DATE NOT NULL,
    TOTAL_AMOUNT DECIMAL(18, 2) NOT NULL,
    PRODUCT_CODE VARCHAR(50) NOT NULL,
    PRODUCT_TYPE VARCHAR(50) NOT NULL
);

-- Creación de la tabla VentasProductoC
CREATE TABLE SalesPC (
    SALE_DATE DATE NOT NULL,
    TOTAL_AMOUNT DECIMAL(18, 2) NOT NULL,
    PRODUCT_CODE VARCHAR(50) NOT NULL,
    PRODUCT_TYPE VARCHAR(50) NOT NULL
);
